name: Tests

on: [push, pull_request]

jobs:

  check:
    name: Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install cuda
        uses: Jimver/cuda-toolkit@v0.2.15
        with:
          cuda: '12.2.0'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        env:
          CUDA_COMPUTE_CAP: '86'
        with:
          command: check
          args: --tests

  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, windows-latest ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Fix LibOpenCL on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install ocl-icd-opencl-dev -y

      - name: Fix CRLF on Windows
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf false

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install CUDA Linux
        if: runner.os == 'Linux'
        uses: Jimver/cuda-toolkit@v0.2.15
        with:
          cuda: '12.2.0'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Install CUDA Windows
        if: runner.os == 'Windows'
        uses: Jimver/cuda-toolkit@v0.2.15
        with:
          cuda: '12.2.0'
          method: 'network'

      - name: Set up MSVC for nvcc (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set NVCC_CCBIN for Windows
        if: runner.os == 'Windows'
        shell: bash
        run: echo "NVCC_CCBIN=cl.exe" >> $GITHUB_ENV

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo test regular features
        uses: actions-rs/cargo@v1
        env:
          CUDA_COMPUTE_CAP: '86'
        with:
          command: test
          args: -p keryx-miner

      - name: Run cargo test no asm
        uses: actions-rs/cargo@v1
        env:
          CUDA_COMPUTE_CAP: '86'
        with:
          command: test
          args: -p keryx-miner --features=no-asm


      - name: Run cargo test no parking_lot
        uses: actions-rs/cargo@v1
        env:
          CUDA_COMPUTE_CAP: '86'
        with:
          command: test
          args: -p keryx-miner --no-default-features

      - name: Run cargo test shuttle
        uses: actions-rs/cargo@v1
        env:
          CUDA_COMPUTE_CAP: '86'
        with:
          command: test
          args: -p keryx-miner --no-default-features --features=shuttle

      - name: Run cargo test for keryxopencl
        uses: actions-rs/cargo@v1
        env:
          CUDA_COMPUTE_CAP: '86'
        with:
          command: test
          args: -p keryxopencl


  test-release:
    name: Test Suite Release
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-22.04, windows-latest ]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Fix LibOpenCL on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install ocl-icd-opencl-dev -y

      - name: Fix CRLF on Windows
        if: runner.os == 'Windows'
        run: git config --global core.autocrlf false

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install CUDA Linux
        if: runner.os == 'Linux'
        uses: Jimver/cuda-toolkit@v0.2.15
        with:
          cuda: '12.2.0'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Install CUDA Windows
        if: runner.os == 'Windows'
        uses: Jimver/cuda-toolkit@v0.2.15
        with:
          cuda: '12.2.0'
          method: 'network'

      - name: Set up MSVC for nvcc (Windows)
        if: runner.os == 'Windows'
        uses: ilammy/msvc-dev-cmd@v1

      - name: Set NVCC_CCBIN for Windows
        if: runner.os == 'Windows'
        shell: bash
        run: echo "NVCC_CCBIN=cl.exe" >> $GITHUB_ENV

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run cargo test release regular features
        uses: actions-rs/cargo@v1
        env:
          CUDA_COMPUTE_CAP: '86'
        with:
          command: test
          args: --release -p keryx-miner

      - name: Run cargo test release no asm
        uses: actions-rs/cargo@v1
        env:
          CUDA_COMPUTE_CAP: '86'
        with:
          command: test
          args: --features=no-asm --release -p keryx-miner

      - name: Run cargo test release no parking_lot
        uses: actions-rs/cargo@v1
        env:
          CUDA_COMPUTE_CAP: '86'
        with:
          command: test
          args: --no-default-features --release -p keryx-miner

      - name: Run cargo test release shuttle
        uses: actions-rs/cargo@v1
        env:
          CUDA_COMPUTE_CAP: '86'
        with:
          command: test
          args: --no-default-features --features=shuttle --release -p keryx-miner

      - name: Run cargo test for keryxopencl
        uses: actions-rs/cargo@v1
        env:
          CUDA_COMPUTE_CAP: '86'
        with:
          command: test
          args: --release -p keryxopencl

  lints:
    name: Lints
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Install cuda
        uses: Jimver/cuda-toolkit@v0.2.15
        with:
          cuda: '12.2.0'
          method: 'network'
          sub-packages: '["nvcc", "cudart"]'

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}


      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        env:
          CUDA_COMPUTE_CAP: '86'
        with:
          command: clippy
          args: --tests -- -D warnings
